name: Release Nuget on Nuget.org

on:
  push:
    tags:
    - "v*"
  workflow_dispatch:

jobs:
  release-nuget:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Verify commit exists in origin/main
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          git branch --remote --contains | grep origin/main

      - name: Get version information from tag
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Pack
        run: dotnet pack src/CommonNovel/CommonNovel.csproj -c Release -p:PackageVersion=${{ steps.get_version.outputs.version-without-v }}

      - name: Push
        run: dotnet nuget push src/CommonNovel/bin/Release/AliceProject.CommonNovel.${{ steps.get_version.outputs.version-without-v }}.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }}
        env:
          GITHUB_TOKEN: ${{ secrets.NUGET_API_KEY }}
